Ran the project through ReSharper
RileyKun/Anubis pull request #2
Opened 2024-04-10 19:47 UTC by Viceroyy

I don't know how "correct" these changes are, but they were suggested by ReSharper. Also, this makes the code use C++ style casts and not C-Style casts, in accordance with the style guidelines.

2024-04-10 20:03 UTC, Viceroyy commented
Ugh I should've used branches; sorry it's been a while since I last used Git.

2024-04-10 20:20 UTC, RileyKun requested changes

2024-04-10 20:20 UTC, RileyKun commented on src/sdk/valve/surface.cpp
I would prefer to not add const to parameters that are not already defined as const within the hl2src leak

2024-04-10 20:20 UTC, RileyKun commented on src/entry_point.cpp
I would prefer to keep the C-Style cast here to keep the code more compact.

2024-04-10 20:20 UTC, RileyKun commented on src/sdk/valve/surface.hpp
Ditto: .cpp

2024-04-10 20:20 UTC, RileyKun commented
> Ugh I should've used branches; sorry it's been a while since I last used Git.

Branches are the least of my worry from people making PRs, don't worry!

2024-04-11 00:01 UTC, RileyKun approved these changes
Looks good now. thanks for the contribution!

2024-04-11 00:01 UTC, merged